services:
    crafty:
        container_name: crafty_container
        image: registry.gitlab.com/crafty-controller/crafty-4:latest
        restart: always
        environment:
            - TZ=Etc/UTC
        ports:
            - "8443:8443" # HTTPS
            - "8123:8123" # DYNMAP
            - "19132:19132/udp" # BEDROCK
            - "25500-25600:25500-25600" # MC SERV PORT RANGE
        volumes:
            - /mnt/Storage2/crafty/backups:/crafty/backups
            - /DATA/AppData/crafty/logs/:/crafty/logs
            - /mnt/Storage2/crafty/servers:/crafty/servers
            - /DATA/AppData/crafty/config/:/crafty/app/config
            - /mnt/Storage2/crafty/import:/crafty/import
